"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, ArrowRight, Bot, Check, ChevronRight, Code2, Copy, Cpu, Download, ExternalLink, GitBranch, GitFork, Laptop, Layers3, Loader2, MessageSquareText, Plus, RefreshCw, Search, Server, Settings2, ShieldCheck, Sparkles, TerminalSquare, Trash2, UserRound, UserRoundCheck, UsersRound, Wifi, WifiOff, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ACTOR_CATALOG, type ActorId } from "@/lib/actors";

type Repository = { id: string; fullName: string; url: string; defaultBranch: string; visibility: string; createdAt: number };
type Worker = { id: string; name: string; platform: string; capabilities: string[]; runtimes: string[]; lastSeenAt: number | null; createdAt: number };
type Task = { id: string; repositoryId: string; title: string; prompt: string; actor: ActorId; model: string | null; mode: "single" | "multi"; runtime: "auto" | "herdr" | "direct"; activeSessionId: string | null; baseBranch: string; workBranch: string | null; status: string; workerId: string | null; attempt: number; summary: string | null; diffStat: string | null; prUrl: string | null; error: string | null; createdAt: number; updatedAt: number };
type AgentSession = { id: string; taskId: string; actor: ActorId; role: string; model: string | null; ordinal: number; status: string; runtime: string | null; runtimeName: string | null; workspaceId: string | null; paneId: string | null; summary: string | null; createdAt: number; updatedAt: number };
type SessionMessage = { id: string; taskId: string; fromSessionId: string | null; toSessionId: string | null; kind: string; body: string; artifacts: string[]; gitRef: string | null; status: string; createdAt: number; deliveredAt: number | null; acknowledgedAt: number | null };
type TaskEvent = { id: number; taskId: string; kind: string; message: string; payload: { compareUrl?: string; sessionId?: string } | null; createdAt: number };
type State = { repositories: Repository[]; workers: Worker[]; tasks: Task[]; events: TaskEvent[]; sessions: AgentSession[]; messages: SessionMessage[]; serverTime: number };
type DraftStep = { actor: ActorId; role: string };

const emptyState: State = { repositories: [], workers: [], tasks: [], events: [], sessions: [], messages: [], serverTime: Date.now() };
const actorVisuals: Record<ActorId, { icon: typeof Bot; tone: string }> = {
  pi: { icon: Sparkles, tone: "violet" },
  codex: { icon: Code2, tone: "cyan" },
  claude: { icon: Bot, tone: "amber" },
  gemini: { icon: Sparkles, tone: "cyan" },
  cursor: { icon: Code2, tone: "violet" },
  copilot: { icon: GitFork, tone: "green" },
  opencode: { icon: TerminalSquare, tone: "cyan" },
  qwen: { icon: Bot, tone: "amber" },
  aider: { icon: Laptop, tone: "green" },
  kimi: { icon: Bot, tone: "violet" },
  kiro: { icon: Layers3, tone: "amber" },
  droid: { icon: Bot, tone: "cyan" },
  amp: { icon: Activity, tone: "violet" },
  devin: { icon: Bot, tone: "violet" },
  cline: { icon: TerminalSquare, tone: "cyan" },
  qodercli: { icon: Code2, tone: "amber" },
};
const actors = ACTOR_CATALOG.map((actor) => ({ ...actor, ...actorVisuals[actor.id] }));
const columns = [
  { key: "queued", title: "Queued", helper: "Waiting for a compatible worker", statuses: ["queued"] },
  { key: "running", title: "Running", helper: "Session or GitHub action in progress", statuses: ["claimed", "running", "resume_requested", "resuming", "publish_requested", "publishing"] },
  { key: "review", title: "Review", helper: "Human decision required", statuses: ["blocked", "review", "failed"] },
  { key: "done", title: "Done", helper: "PR created or task closed", statuses: ["done", "cancelled"] },
];
const statusLabels: Record<string, string> = { queued: "Queued", claimed: "Claimed", running: "Running", blocked: "Agent blocked", resume_requested: "Reply queued", resuming: "Resuming", review: "Needs review", publish_requested: "Creating PR", publishing: "Creating PR", done: "PR created", failed: "Failed", cancelled: "Cancelled" };

async function requestJson<T>(url: string, init?: RequestInit): Promise<T> {
  const response = await fetch(url, { ...init, headers: { "content-type": "application/json", ...(init?.headers || {}) } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error || `Request failed (${response.status})`);
  return body as T;
}

export default function AgentConsole() {
  const [state, setState] = useState<State>(emptyState);
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState<string | null>(null);
  const [query, setQuery] = useState("");
  const [createOpen, setCreateOpen] = useState(false);
  const [repoOpen, setRepoOpen] = useState(false);
  const [workerOpen, setWorkerOpen] = useState(false);
  const [selected, setSelected] = useState<Task | null>(null);
  const [actor, setActor] = useState<ActorId>("codex");
  const [mode, setMode] = useState<"single" | "multi">("single");
  const [runtime, setRuntime] = useState<"auto" | "herdr" | "direct">("auto");
  const [teamSteps, setTeamSteps] = useState<DraftStep[]>([
    { actor: "claude", role: "Planner" },
    { actor: "codex", role: "Implementer" },
    { actor: "pi", role: "Reviewer" },
  ]);
  const [repositoryId, setRepositoryId] = useState("");
  const [enrollment, setEnrollment] = useState<{ token: string; name: string } | null>(null);
  const [busy, setBusy] = useState(false);

  const refresh = useCallback(async (quiet = false) => {
    try {
      const next = await requestJson<State>("/api/state", { cache: "no-store" });
      setState(next);
      setSelected((current) => current ? next.tasks.find((task) => task.id === current.id) || null : null);
      if (!quiet) setNotice(null);
    } catch (error) {
      if (!quiet) setNotice(error instanceof Error ? error.message : "Could not load workspace");
    } finally { setLoading(false); }
  }, []);
  useEffect(() => { void refresh(); const timer = setInterval(() => void refresh(true), 4000); return () => clearInterval(timer); }, [refresh]);
  useEffect(() => { if (!repositoryId && state.repositories[0]) setRepositoryId(state.repositories[0].id); }, [state.repositories, repositoryId]);

  const eventsByTask = useMemo(() => {
    const grouped = new Map<string, TaskEvent[]>();
    state.events.forEach((event) => grouped.set(event.taskId, [...(grouped.get(event.taskId) || []), event]));
    return grouped;
  }, [state.events]);
  const sessionsByTask = useMemo(() => {
    const grouped = new Map<string, AgentSession[]>();
    state.sessions.forEach((session) => grouped.set(session.taskId, [...(grouped.get(session.taskId) || []), session]));
    return grouped;
  }, [state.sessions]);
  const messagesByTask = useMemo(() => {
    const grouped = new Map<string, SessionMessage[]>();
    state.messages.forEach((message) => grouped.set(message.taskId, [...(grouped.get(message.taskId) || []), message]));
    return grouped;
  }, [state.messages]);
  const visibleTasks = useMemo(() => {
    const needle = query.trim().toLowerCase();
    return needle ? state.tasks.filter((task) => `${task.title} ${task.actor} ${task.mode} ${task.id}`.toLowerCase().includes(needle)) : state.tasks;
  }, [state.tasks, query]);
  const onlineWorkers = state.workers.filter((worker) => worker.lastSeenAt && state.serverTime - worker.lastSeenAt < 15000);
  const repoById = new Map(state.repositories.map((repo) => [repo.id, repo]));
  const workerById = new Map(state.workers.map((worker) => [worker.id, worker]));

  async function addRepository(form: FormData) {
    setBusy(true);
    try {
      await requestJson("/api/repositories", { method: "POST", body: JSON.stringify({ fullName: form.get("fullName"), defaultBranch: form.get("defaultBranch"), visibility: form.get("visibility") }) });
      setRepoOpen(false); setNotice("GitHub repository connected"); await refresh(true);
    } catch (error) { setNotice(error instanceof Error ? error.message : "Could not connect repository"); }
    finally { setBusy(false); }
  }
  async function addTask(form: FormData) {
    setBusy(true);
    try {
      await requestJson("/api/tasks", { method: "POST", body: JSON.stringify({ repositoryId, actor, mode, runtime, steps: mode === "multi" ? teamSteps : undefined, title: form.get("title"), prompt: form.get("prompt"), model: form.get("model"), baseBranch: form.get("baseBranch") }) });
      setCreateOpen(false); setNotice(mode === "multi" ? `${teamSteps.length}-agent workflow queued` : "Single-agent task queued"); await refresh(true);
    } catch (error) { setNotice(error instanceof Error ? error.message : "Could not create task"); }
    finally { setBusy(false); }
  }
  async function enrollWorker(form: FormData) {
    setBusy(true);
    try {
      const result = await requestJson<{ worker: { name: string }; token: string }>("/api/workers/enroll", { method: "POST", body: JSON.stringify({ name: form.get("name") }) });
      setEnrollment({ token: result.token, name: result.worker.name }); await refresh(true);
    } catch (error) { setNotice(error instanceof Error ? error.message : "Could not create worker token"); }
    finally { setBusy(false); }
  }
  async function act(task: Task, action: "approve" | "retry" | "cancel" | "respond", reply?: string) {
    setBusy(true);
    try { await requestJson(`/api/tasks/${task.id}/action`, { method: "POST", body: JSON.stringify({ action, reply }) }); await refresh(true); setNotice(action === "approve" ? "Approved. The worker will create a GitHub pull request." : action === "retry" ? "Task queued for another run." : action === "respond" ? "Response queued for the blocked Herdr session." : "Task cancelled."); }
    catch (error) { setNotice(error instanceof Error ? error.message : "Action failed"); }
    finally { setBusy(false); }
  }

  return (
    <main className="min-h-screen bg-[#080a11] text-[#f4f5f8]">
      <header className="border-b border-white/8 bg-[#0b0e17]/90 px-4 py-3 backdrop-blur md:px-7"><div className="mx-auto flex max-w-[1600px] items-center justify-between gap-4">
        <div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-gradient-to-br from-violet-500 to-fuchsia-500 shadow-[0_0_30px_rgba(139,92,246,.35)]"><Sparkles className="size-5" /></div><div><div className="text-[15px] font-semibold tracking-tight">TeamWeave</div><div className="text-[11px] text-white/40">Agent delivery console</div></div></div>
        <div className={`hidden items-center gap-2 rounded-full border px-3 py-1.5 text-xs sm:flex ${onlineWorkers.length ? "border-emerald-400/15 bg-emerald-400/8 text-emerald-300" : "border-white/8 bg-white/4 text-white/40"}`}>{onlineWorkers.length ? <Wifi className="size-3.5" /> : <WifiOff className="size-3.5" />}{onlineWorkers.length} worker{onlineWorkers.length === 1 ? "" : "s"} online</div>
        <div className="flex items-center gap-2"><Button variant="ghost" size="icon" className="text-white/60 hover:bg-white/8 hover:text-white" onClick={() => setWorkerOpen(true)} aria-label="Worker setup"><Settings2 /></Button><div className="grid size-9 place-items-center rounded-full bg-[#24283a] text-xs font-semibold">LE</div></div>
      </div></header>

      <div className="mx-auto max-w-[1600px] px-4 py-5 md:px-7 md:py-7">
        <Tabs defaultValue="board" className="gap-6">
          <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end">
            <div><div className="mb-2 flex items-center gap-2 text-xs font-medium uppercase tracking-[.16em] text-violet-300"><Activity className="size-3.5" /> Herdr sessions · durable handoffs</div><h1 className="text-2xl font-semibold tracking-[-.03em] md:text-3xl">Agent work console</h1><p className="mt-1.5 max-w-2xl text-sm text-white/45">Run a mainstream coding agent or compose a multi-agent workflow. Each session and handoff stays attached to the task.</p></div>
            <TabsList variant="line" className="h-auto max-w-full justify-start overflow-x-auto border-b border-white/8 text-white/45"><TabsTrigger value="board" className="px-4 py-2.5 text-white/45 data-[state=active]:text-white">Board</TabsTrigger><TabsTrigger value="repositories" className="px-4 py-2.5 text-white/45 data-[state=active]:text-white">Repositories</TabsTrigger><TabsTrigger value="workers" className="px-4 py-2.5 text-white/45 data-[state=active]:text-white">Workers</TabsTrigger><TabsTrigger value="activity" className="px-4 py-2.5 text-white/45 data-[state=active]:text-white">Activity</TabsTrigger></TabsList>
          </div>

          {notice && <div className="flex items-center justify-between rounded-xl border border-violet-400/20 bg-violet-400/8 px-4 py-3 text-sm text-violet-100"><span>{notice}</span><button onClick={() => setNotice(null)} aria-label="Dismiss"><XCircle className="size-4" /></button></div>}

          <TabsContent value="board" className="space-y-5">
            <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={Bot} label="Active sessions" value={String(state.sessions.filter((session) => ["starting", "working", "blocked"].includes(session.status)).length)} tone="violet" /><Stat icon={Cpu} label="Workers online" value={`${onlineWorkers.length} / ${state.workers.length}`} tone="cyan" /><Stat icon={UserRoundCheck} label="Needs attention" value={String(state.tasks.filter((task) => ["blocked", "review"].includes(task.status)).length)} tone="amber" /><Stat icon={GitFork} label="Pull requests" value={String(state.tasks.filter((task) => !!task.prUrl).length)} tone="green" /></section>
            <section className="flex flex-col gap-3 rounded-2xl border border-white/8 bg-white/[.025] p-3 sm:flex-row sm:items-center sm:justify-between"><div className="relative flex-1 sm:max-w-sm"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-white/30" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="h-10 w-full rounded-xl border border-white/8 bg-[#0c0f19] pl-10 pr-3 text-sm outline-none placeholder:text-white/25 focus:border-violet-400/50" placeholder="Search tasks or actors" /></div><div className="flex gap-2"><Button variant="outline" onClick={() => setRepoOpen(true)} className="h-10 border-white/10 bg-transparent text-white hover:bg-white/8"><GitFork /> Connect repo</Button><Button onClick={() => state.repositories.length ? setCreateOpen(true) : setRepoOpen(true)} className="h-10 bg-violet-500 text-white hover:bg-violet-400"><Plus /> New task</Button></div></section>
            {loading ? <Loading /> : state.repositories.length === 0 ? <Empty icon={GitFork} title="Connect a GitHub repository" text="TeamWeave stores only the repository address. GitHub authentication remains on your local worker." action="Connect repository" onAction={() => setRepoOpen(true)} /> : state.workers.length === 0 ? <Empty icon={Laptop} title="Register your local worker" text="The worker runs persistent Herdr sessions or falls back to direct agent CLIs." action="Set up worker" onAction={() => setWorkerOpen(true)} /> : <section className="grid items-start gap-4 xl:grid-cols-4">{columns.map((column) => <div key={column.key} className="rounded-2xl border border-white/8 bg-[#0d101a] p-3"><div className="mb-3 flex items-center justify-between px-1"><div><h2 className="text-sm font-semibold">{column.title}</h2><p className="mt-0.5 text-xs text-white/35">{column.helper}</p></div><span className="rounded-full bg-white/6 px-2 py-1 text-xs text-white/45">{visibleTasks.filter((task) => column.statuses.includes(task.status)).length}</span></div><div className="space-y-3">{visibleTasks.filter((task) => column.statuses.includes(task.status)).map((task) => <TaskCard key={task.id} task={task} sessions={sessionsByTask.get(task.id) || []} repo={repoById.get(task.repositoryId)} worker={task.workerId ? workerById.get(task.workerId) : undefined} onOpen={() => setSelected(task)} />)}{visibleTasks.filter((task) => column.statuses.includes(task.status)).length === 0 && <div className="rounded-xl border border-dashed border-white/8 px-3 py-8 text-center text-xs text-white/25">No tasks</div>}</div></div>)}</section>}
          </TabsContent>

          <TabsContent value="repositories"><section className="space-y-4"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Connected repositories</h2><p className="mt-1 text-sm text-white/40">Git credentials never leave your worker machine.</p></div><Button onClick={() => setRepoOpen(true)} className="bg-violet-500 text-white hover:bg-violet-400"><Plus /> Connect</Button></div>{state.repositories.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{state.repositories.map((repo) => <article key={repo.id} className="rounded-2xl border border-white/8 bg-[#0d101a] p-5"><div className="flex items-start justify-between"><div className="grid size-10 place-items-center rounded-xl bg-white/6"><GitFork className="size-5" /></div><span className="rounded-full bg-white/6 px-2 py-1 text-xs capitalize text-white/45">{repo.visibility}</span></div><h3 className="mt-5 font-semibold">{repo.fullName}</h3><div className="mt-3 flex items-center gap-2 text-xs text-white/38"><GitBranch className="size-3.5" />{repo.defaultBranch}</div><a href={`https://github.com/${repo.fullName}`} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-1.5 text-sm text-violet-300 hover:text-violet-200">Open on GitHub <ExternalLink className="size-3.5" /></a></article>)}</div> : <Empty icon={GitFork} title="No repositories yet" text="Connect a public or private GitHub repository by its owner/name." action="Connect repository" onAction={() => setRepoOpen(true)} />}</section></TabsContent>

          <TabsContent value="workers"><section className="space-y-4"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Execution workers</h2><p className="mt-1 text-sm text-white/40">Workers detect installed actors and the Herdr runtime automatically.</p></div><Button onClick={() => setWorkerOpen(true)} className="bg-violet-500 text-white hover:bg-violet-400"><Plus /> Register worker</Button></div>{state.workers.length ? <div className="grid gap-4 lg:grid-cols-3">{state.workers.map((worker) => { const online = !!worker.lastSeenAt && state.serverTime - worker.lastSeenAt < 15000; return <article key={worker.id} className="rounded-2xl border border-white/8 bg-[#0d101a] p-5"><div className="flex items-start justify-between"><div className="grid size-10 place-items-center rounded-xl bg-cyan-400/10 text-cyan-300"><Server className="size-5" /></div><span className={`flex items-center gap-1.5 text-xs ${online ? "text-emerald-300" : "text-white/35"}`}><span className={`size-1.5 rounded-full ${online ? "bg-emerald-300" : "bg-white/25"}`} />{online ? "Online" : "Offline"}</span></div><h3 className="mt-5 font-semibold">{worker.name}</h3><p className="mt-1 truncate text-xs text-white/35">{worker.platform}</p><div className="mt-5 flex flex-wrap gap-2">{worker.runtimes?.map((runtime) => <span key={runtime} className={`rounded-lg px-2.5 py-1.5 text-xs ${runtime === "herdr" ? "bg-violet-400/12 text-violet-200" : "bg-white/6 text-white/55"}`}>{runtime === "herdr" ? "Herdr" : "Direct"}</span>)}{worker.capabilities.length ? worker.capabilities.map((actor) => <span key={actor} className="rounded-lg bg-white/6 px-2.5 py-1.5 text-xs capitalize text-white/65">{actors.find((item) => item.id === actor)?.name || actor}</span>) : <span className="text-xs text-amber-300/70">Worker has not connected yet</span>}</div></article>; })}</div> : <Empty icon={Server} title="No workers registered" text="Register this Mac with any supported coding agent installed, such as Codex, Claude, Gemini, Cursor, Copilot, OpenCode, Qwen, or Aider." action="Set up worker" onAction={() => setWorkerOpen(true)} />}</section></TabsContent>

          <TabsContent value="activity"><section className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="rounded-2xl border border-white/8 bg-[#0d101a] p-5"><h2 className="font-semibold">Execution events</h2><div className="mt-5">{state.events.length ? state.events.slice(0, 80).map((event) => <div key={event.id} className="flex gap-4 border-l border-white/8 py-3 pl-5"><div className="mt-1 size-2 shrink-0 rounded-full bg-violet-400 shadow-[0_0_10px_rgba(167,139,250,.6)]" /><div><p className="whitespace-pre-wrap text-sm text-white/72">{event.message}</p><p className="mt-1 text-xs text-white/30">{event.kind} · {relative(event.createdAt)}</p></div></div>) : <p className="py-12 text-center text-sm text-white/30">Events appear when you create a task.</p>}</div></div><div className="rounded-2xl border border-violet-400/15 bg-gradient-to-b from-violet-500/10 to-transparent p-5"><ShieldCheck className="size-7 text-violet-300" /><h2 className="mt-4 font-semibold">Control boundary</h2><p className="mt-2 text-sm leading-6 text-white/45">Herdr keeps terminal sessions alive. TeamWeave stores every handoff, isolates Git changes, and still requires approval before creating a pull request.</p><div className="mt-5 space-y-3 text-sm"><Control label="Durable session messages" /><Control label="One isolated branch" /><Control label="Explicit PR approval" /></div></div></section></TabsContent>
        </Tabs>
      </div>

      <Dialog open={repoOpen} onOpenChange={setRepoOpen}><DialogContent className="border-white/10 bg-[#121622] text-white sm:max-w-lg"><DialogHeader><DialogTitle>Connect GitHub repository</DialogTitle><DialogDescription className="text-white/42">Use owner/repository. Private access is checked by GitHub CLI on your local worker.</DialogDescription></DialogHeader><form action={addRepository} className="space-y-4"><Field label="Repository"><input name="fullName" className="field" placeholder="owner/repository" required autoFocus /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Default branch"><input name="defaultBranch" className="field" defaultValue="main" required /></Field><Field label="Visibility"><select name="visibility" className="field"><option value="unknown">Auto / unknown</option><option value="public">Public</option><option value="private">Private</option></select></Field></div><DialogFooter><Button type="button" variant="ghost" onClick={() => setRepoOpen(false)} className="text-white/55 hover:bg-white/8 hover:text-white">Cancel</Button><Button disabled={busy} className="bg-violet-500 text-white hover:bg-violet-400">{busy && <Loader2 className="animate-spin" />}<GitFork /> Connect</Button></DialogFooter></form></DialogContent></Dialog>

      <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent className="max-h-[92vh] overflow-y-auto border-white/10 bg-[#121622] text-white sm:max-w-2xl"><DialogHeader><DialogTitle>Create agent task</DialogTitle><DialogDescription className="text-white/42">Choose one agent for focused work or a sequence of sessions with durable handoffs.</DialogDescription></DialogHeader><form action={addTask} className="space-y-5">
        <div className="grid grid-cols-2 gap-2 rounded-xl bg-[#090c13] p-1.5"><button type="button" onClick={() => setMode("single")} className={`flex items-center justify-center gap-2 rounded-lg px-3 py-2.5 text-sm transition ${mode === "single" ? "bg-violet-500 text-white" : "text-white/45 hover:bg-white/5"}`}><UserRound className="size-4" />Single agent</button><button type="button" onClick={() => setMode("multi")} className={`flex items-center justify-center gap-2 rounded-lg px-3 py-2.5 text-sm transition ${mode === "multi" ? "bg-violet-500 text-white" : "text-white/45 hover:bg-white/5"}`}><UsersRound className="size-4" />Agent workflow</button></div>
        {mode === "single" ? <div className="grid gap-3 sm:grid-cols-3 xl:grid-cols-4">{actors.map((item) => <button type="button" key={item.id} onClick={() => setActor(item.id)} className={`rounded-xl border p-3 text-left transition ${actor === item.id ? "border-violet-400/55 bg-violet-400/10" : "border-white/8 bg-white/[.025] hover:bg-white/5"}`}><div className={`grid size-8 place-items-center rounded-lg actor-${item.tone}`}><item.icon className="size-4" /></div><div className="mt-3 text-sm font-medium">{item.name}</div><div className="mt-1 text-[11px] leading-4 text-white/35">{item.detail}</div><div className="mt-2 flex flex-wrap gap-1">{item.runtimes.map((itemRuntime) => <span key={itemRuntime} className="rounded bg-white/6 px-1.5 py-0.5 text-[10px] uppercase tracking-wide text-white/35">{itemRuntime}</span>)}</div></button>)}</div> : <div className="space-y-2"><div className="flex items-center justify-between"><span className="text-xs font-medium text-white/52">Session order</span><span className="text-[11px] text-white/28">Each stage receives the previous handoff</span></div>{teamSteps.map((step, index) => <div key={index} className="grid grid-cols-[28px_1fr_140px_34px] items-center gap-2 rounded-xl border border-white/8 bg-white/[.025] p-2"><div className="grid size-7 place-items-center rounded-lg bg-violet-400/10 text-xs text-violet-200">{index + 1}</div><input value={step.role} onChange={(event) => setTeamSteps((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, role: event.target.value } : item))} className="field h-9" aria-label={`Role for session ${index + 1}`} /><select value={step.actor} onChange={(event) => setTeamSteps((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, actor: event.target.value as ActorId } : item))} className="field h-9" aria-label={`Actor for session ${index + 1}`}>{actors.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button type="button" disabled={teamSteps.length <= 2} onClick={() => setTeamSteps((current) => current.filter((_, itemIndex) => itemIndex !== index))} className="grid size-8 place-items-center rounded-lg text-white/30 hover:bg-white/6 hover:text-rose-300 disabled:cursor-not-allowed disabled:opacity-20" aria-label={`Remove session ${index + 1}`}><Trash2 className="size-4" /></button></div>)}{teamSteps.length < 4 && <button type="button" onClick={() => setTeamSteps((current) => [...current, { actor: "codex", role: `Agent ${current.length + 1}` }])} className="flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-white/10 py-2.5 text-xs text-white/38 hover:border-violet-400/30 hover:text-violet-200"><Plus className="size-3.5" />Add session</button>}</div>}
        <div className="grid gap-4 sm:grid-cols-2"><Field label="Repository"><Select value={repositoryId} onValueChange={(value) => value && setRepositoryId(value)}><SelectTrigger className="field h-10 w-full"><SelectValue placeholder="Select repository" /></SelectTrigger><SelectContent>{state.repositories.map((repo) => <SelectItem key={repo.id} value={repo.id}>{repo.fullName}</SelectItem>)}</SelectContent></Select></Field><Field label="Base branch"><input name="baseBranch" className="field" defaultValue={repoById.get(repositoryId)?.defaultBranch || "main"} required /></Field></div>
        <div className="grid gap-4 sm:grid-cols-2"><Field label="Runtime"><Select value={runtime} onValueChange={(value) => value && setRuntime(value as "auto" | "herdr" | "direct")}><SelectTrigger className="field h-10 w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="auto">Auto · best available per actor</SelectItem><SelectItem value="herdr">Require Herdr</SelectItem><SelectItem value="direct">Direct CLI</SelectItem></SelectContent></Select></Field>{mode === "single" ? <Field label="Model override (optional)"><input name="model" className="field" placeholder={actors.find((item) => item.id === actor)?.modelHint || "Use CLI default"} /></Field> : <div className="rounded-xl border border-violet-400/12 bg-violet-400/6 p-3 text-xs leading-5 text-violet-100/55">All sessions share one isolated branch and run in order. Auto mode can mix Herdr and direct adapters when a workflow needs it.</div>}</div>
        <Field label="Task title"><input name="title" className="field" placeholder="Fix session restore race" required /></Field><Field label="Instructions"><textarea name="prompt" className="field min-h-32 resize-y" placeholder="Describe the goal, constraints, and checks the agent should run…" required /></Field>
        <DialogFooter><Button type="button" variant="ghost" onClick={() => setCreateOpen(false)} className="text-white/55 hover:bg-white/8 hover:text-white">Cancel</Button><Button disabled={busy || !repositoryId || (mode === "multi" && teamSteps.some((step) => !step.role.trim()))} className="bg-violet-500 text-white hover:bg-violet-400">{busy && <Loader2 className="animate-spin" />}<Plus /> Queue {mode === "multi" ? "workflow" : "task"}</Button></DialogFooter>
      </form></DialogContent></Dialog>

      <Dialog open={workerOpen} onOpenChange={(open) => { setWorkerOpen(open); if (!open) setEnrollment(null); }}><DialogContent className="max-h-[92vh] overflow-y-auto border-white/10 bg-[#121622] text-white sm:max-w-2xl"><DialogHeader><DialogTitle>Register local worker</DialogTitle><DialogDescription className="text-white/42">Run one small Node process beside Herdr, your coding agents, and local GitHub credentials.</DialogDescription></DialogHeader>{!enrollment ? <form action={enrollWorker} className="space-y-5"><div className="grid gap-3 sm:grid-cols-4"><div className="rounded-xl border border-violet-400/18 bg-violet-400/7 p-3"><Layers3 className="size-4 text-violet-300" /><div className="mt-2 text-sm">Herdr</div><div className="mt-1 text-[11px] text-white/35">Preferred runtime</div></div>{actors.map((item) => <div key={item.id} className="rounded-xl border border-white/8 bg-white/[.025] p-3"><item.icon className="size-4 text-violet-300" /><div className="mt-2 text-sm">{item.name}</div><div className="mt-1 text-[11px] text-white/35">Auto-detected</div></div>)}</div><Field label="Worker name"><input name="name" className="field" defaultValue="My Mac" required /></Field><div className="rounded-xl border border-amber-400/15 bg-amber-400/6 p-4 text-xs leading-5 text-amber-100/65">Authenticate GitHub with <code>gh auth login</code> and <code>gh auth setup-git</code>. Start Herdr once for persistent sessions, or let the worker use direct CLI fallback.</div><DialogFooter><Button disabled={busy} className="bg-violet-500 text-white hover:bg-violet-400">{busy && <Loader2 className="animate-spin" />} Generate worker token</Button></DialogFooter></form> : <WorkerInstructions enrollment={enrollment} />}</DialogContent></Dialog>

      <Dialog open={!!selected} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="max-h-[92vh] overflow-y-auto border-white/10 bg-[#10141f] text-white sm:max-w-3xl">{selected && <TaskDetail task={selected} repo={repoById.get(selected.repositoryId)} worker={selected.workerId ? workerById.get(selected.workerId) : undefined} events={eventsByTask.get(selected.id) || []} sessions={sessionsByTask.get(selected.id) || []} messages={messagesByTask.get(selected.id) || []} busy={busy} onAction={act} />}</DialogContent></Dialog>
    </main>
  );
}

function TaskCard({ task, sessions, repo, worker, onOpen }: { task: Task; sessions: AgentSession[]; repo?: Repository; worker?: Worker; onOpen: () => void }) {
  const primaryActor = actors.find((item) => item.id === task.actor)!;
  return <button onClick={onOpen} className="group w-full rounded-xl border border-white/8 bg-[#141824] p-3.5 text-left transition hover:-translate-y-0.5 hover:border-violet-400/30 hover:bg-[#171b29]"><div className="flex items-center justify-between"><span className={`status status-${task.status}`}>{statusLabels[task.status] || task.status}</span><span className="font-mono text-[10px] text-white/25">{task.id.slice(-6)}</span></div><h3 className="mt-3 text-sm font-medium leading-5 text-white/90">{task.title}</h3><p className="mt-1.5 truncate text-xs text-white/34">{repo?.fullName || "Unknown repository"}</p><div className="mt-3 flex items-center justify-between border-t border-white/6 pt-3 text-[11px]"><span className="flex items-center gap-1.5 text-white/55">{task.mode === "multi" ? <UsersRound className="size-3.5" /> : <primaryActor.icon className="size-3.5" />}{task.mode === "multi" ? `${sessions.length}-agent workflow` : primaryActor.name}</span><span className="text-white/28">{relative(task.updatedAt)}</span></div>{sessions.length > 1 && <div className="mt-2 flex items-center gap-1">{sessions.map((session, index) => <span key={session.id} className="flex items-center gap-1 text-[10px] text-white/32"><span className={`size-1.5 rounded-full ${session.status === "done" ? "bg-emerald-300" : session.status === "blocked" ? "bg-amber-300" : ["starting", "working"].includes(session.status) ? "bg-cyan-300" : "bg-white/20"}`} />{session.role}{index < sessions.length - 1 && <ArrowRight className="size-2.5 text-white/15" />}</span>)}</div>}{worker && <div className="mt-2 flex items-center gap-1.5 text-[11px] text-white/30"><Cpu className="size-3" />{worker.name}</div>}</button>;
}

function TaskDetail({ task, repo, worker, events, sessions, messages, busy, onAction }: { task: Task; repo?: Repository; worker?: Worker; events: TaskEvent[]; sessions: AgentSession[]; messages: SessionMessage[]; busy: boolean; onAction: (task: Task, action: "approve" | "retry" | "cancel" | "respond", reply?: string) => void }) {
  const [reply, setReply] = useState("");
  const compareUrl = [...events].reverse().find((event) => event.payload?.compareUrl)?.payload?.compareUrl;
  const sessionById = new Map(sessions.map((session) => [session.id, session]));
  return <><DialogHeader><div className="mb-1 flex flex-wrap items-center gap-2 text-xs text-white/35"><span>{task.id}</span><span>·</span><span>{statusLabels[task.status] || task.status}</span><span>·</span><span>{task.mode === "multi" ? `${sessions.length} sessions` : "single session"}</span><span>·</span><span>attempt {task.attempt}</span></div><DialogTitle className="text-xl">{task.title}</DialogTitle><DialogDescription className="whitespace-pre-wrap pt-1 leading-6 text-white/45">{task.prompt}</DialogDescription></DialogHeader>
    <div className="grid gap-3 sm:grid-cols-3"><Meta icon={GitFork} label="Repository" value={repo?.fullName || "Unknown"} /><Meta icon={Layers3} label="Runtime" value={task.runtime === "auto" ? "Auto · Herdr preferred" : task.runtime} /><Meta icon={GitBranch} label="Branch" value={task.workBranch || task.baseBranch} /></div>
    <section className="rounded-xl border border-white/8 bg-white/[.025] p-4"><h3 className="flex items-center gap-2 text-sm font-medium"><UsersRound className="size-4 text-violet-300" />Session pipeline</h3><div className="mt-4 space-y-2">{sessions.map((session, index) => { const actorInfo = actors.find((item) => item.id === session.actor) || actors[0]; return <div key={session.id} className={`rounded-xl border p-3 ${task.activeSessionId === session.id ? "border-cyan-400/25 bg-cyan-400/6" : "border-white/7 bg-[#0b0e16]"}`}><div className="flex items-center gap-3"><div className={`grid size-8 shrink-0 place-items-center rounded-lg actor-${actorInfo.tone}`}><actorInfo.icon className="size-4" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-medium">{index + 1}. {session.role}</span><span className="text-xs capitalize text-white/35">{actorInfo.name}</span></div><div className="mt-1 flex flex-wrap items-center gap-2 text-[11px] text-white/28"><span className={`status status-${session.status}`}>{session.status}</span>{session.runtime && <span>{session.runtime}</span>}{session.runtimeName && <span className="font-mono">{session.runtimeName}</span>}</div></div>{index < sessions.length - 1 && <ArrowRight className="size-4 shrink-0 text-white/18" />}</div>{session.status === "blocked" && session.summary && <pre className="mt-3 max-h-32 overflow-y-auto whitespace-pre-wrap rounded-lg bg-amber-400/5 p-3 font-mono text-[11px] leading-5 text-amber-100/55">{session.summary}</pre>}</div>; })}</div></section>
    {messages.length > 0 && <section className="rounded-xl border border-white/8 bg-[#090c13] p-4"><h3 className="flex items-center gap-2 text-sm font-medium"><MessageSquareText className="size-4 text-violet-300" />Cross-session messages</h3><div className="mt-4 space-y-3">{messages.map((message) => <div key={message.id} className="rounded-lg border border-white/6 bg-white/[.025] p-3"><div className="flex flex-wrap items-center gap-2 text-[11px] text-white/32"><span>{message.fromSessionId ? sessionById.get(message.fromSessionId)?.role || "Agent" : "Operator"}</span><ArrowRight className="size-3" /><span>{message.toSessionId ? sessionById.get(message.toSessionId)?.role || "Agent" : "Workflow"}</span><span>·</span><span>{message.status}</span>{message.gitRef && <span className="font-mono text-violet-300/65">{message.gitRef}</span>}</div><p className="mt-2 whitespace-pre-wrap text-xs leading-5 text-white/50">{message.body}</p>{message.artifacts.length > 0 && <div className="mt-2 flex flex-wrap gap-1.5">{message.artifacts.map((artifact) => <span key={artifact} className="rounded-md bg-white/5 px-2 py-1 font-mono text-[10px] text-cyan-100/45">{artifact}</span>)}</div>}</div>)}</div></section>}
    {task.status === "blocked" && <form onSubmit={(event) => { event.preventDefault(); if (reply.trim()) { onAction(task, "respond", reply.trim()); setReply(""); } }} className="rounded-xl border border-amber-400/18 bg-amber-400/6 p-4"><h3 className="text-sm font-medium text-amber-100">Agent needs input</h3><p className="mt-1 text-xs leading-5 text-amber-100/50">Your response is stored as a durable message and delivered to the same Herdr session.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><textarea value={reply} onChange={(event) => setReply(event.target.value)} className="field min-h-20 flex-1 resize-y" placeholder="Answer the question or approve the requested action…" required /><Button disabled={busy || !reply.trim()} className="self-end bg-amber-400 text-[#171006] hover:bg-amber-300"><MessageSquareText />Send response</Button></div></form>}
    {task.summary && <section className="rounded-xl border border-white/8 bg-white/[.025] p-4"><h3 className="text-sm font-medium">Workflow summary</h3><pre className="mt-3 whitespace-pre-wrap font-sans text-sm leading-6 text-white/55">{task.summary}</pre></section>}{task.diffStat && <section className="rounded-xl border border-white/8 bg-[#090c13] p-4"><h3 className="flex items-center gap-2 text-sm font-medium"><GitBranch className="size-4 text-violet-300" />Changed files</h3><pre className="mt-3 overflow-x-auto whitespace-pre-wrap font-mono text-xs leading-5 text-cyan-100/60">{task.diffStat}</pre>{compareUrl && <a href={compareUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1.5 text-sm text-violet-300">Inspect branch on GitHub <ExternalLink className="size-3.5" /></a>}</section>}{task.error && <section className="rounded-xl border border-rose-400/15 bg-rose-400/6 p-4 text-sm leading-6 text-rose-100/70">{task.error}</section>}
    <section className="rounded-xl border border-white/8 bg-[#090c13] p-4"><h3 className="mb-3 flex items-center gap-2 text-sm font-medium"><TerminalSquare className="size-4 text-cyan-300" />Execution log {worker && <span className="font-normal text-white/30">· {worker.name}</span>}</h3><div className="max-h-64 space-y-3 overflow-y-auto font-mono text-xs">{events.length ? events.map((event) => <div key={event.id} className="flex gap-3"><span className="shrink-0 text-white/18">{new Date(event.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span><span className="whitespace-pre-wrap text-white/48">{event.message}</span></div>) : <span className="text-white/30">Waiting for first event…</span>}</div></section>
    <DialogFooter>{["queued", "failed"].includes(task.status) && <Button variant="ghost" disabled={busy} onClick={() => onAction(task, task.status === "failed" ? "retry" : "cancel")} className="text-white/50 hover:bg-white/8 hover:text-white">{task.status === "failed" ? <><RefreshCw /> Retry</> : "Cancel task"}</Button>}{task.status === "review" && <><Button variant="outline" disabled={busy} onClick={() => onAction(task, "retry")} className="border-white/10 bg-transparent text-white hover:bg-white/8"><RefreshCw /> Request changes</Button><Button disabled={busy} onClick={() => onAction(task, "approve")} className="bg-violet-500 text-white hover:bg-violet-400"><Check /> Approve & create PR</Button></>}{task.prUrl && <Button asChild className="bg-emerald-500 text-white hover:bg-emerald-400"><a href={task.prUrl} target="_blank" rel="noreferrer"><GitFork /> Open pull request</a></Button>}</DialogFooter></>;
}
function WorkerInstructions({ enrollment }: { enrollment: { token: string; name: string } }) {
  const [copied, setCopied] = useState(false);
  const origin = typeof window === "undefined" ? "" : window.location.origin;
  const command = `curl -fsSLo agentmux-worker.mjs ${origin}/agentmux-worker.mjs && AGENTMUX_URL=${origin} AGENTMUX_TOKEN=${enrollment.token} node agentmux-worker.mjs`;
  return <div className="space-y-5"><div className="rounded-xl border border-emerald-400/15 bg-emerald-400/6 p-4"><div className="flex items-center gap-2 text-sm font-medium text-emerald-200"><Check className="size-4" />{enrollment.name} registered</div><p className="mt-2 text-xs leading-5 text-emerald-100/50">This token is shown once. Start the worker now or store it in your local password manager.</p></div><div><div className="mb-2 text-xs font-medium text-white/50">Run in Terminal</div><div className="relative rounded-xl border border-white/8 bg-[#080a11] p-4 pr-12"><code className="break-all text-xs leading-6 text-cyan-100/70">{command}</code><button onClick={async () => { await navigator.clipboard.writeText(command); setCopied(true); setTimeout(() => setCopied(false), 1500); }} className="absolute right-3 top-3 grid size-8 place-items-center rounded-lg bg-white/6 text-white/45 hover:text-white" aria-label="Copy command">{copied ? <Check className="size-4" /> : <Copy className="size-4" />}</button></div></div><div className="grid gap-3 sm:grid-cols-3"><Step number="1" text="Install Herdr and run herdr once" /><Step number="2" text="Sign into agents and GitHub CLI" /><Step number="3" text="Paste the worker command" /></div><div className="flex flex-wrap gap-4"><a href="https://herdr.dev/docs/install/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm text-violet-300 hover:text-violet-200"><ExternalLink className="size-4" />Install Herdr</a><a href="/agentmux-worker.mjs" download className="inline-flex items-center gap-2 text-sm text-violet-300 hover:text-violet-200"><Download className="size-4" />Download worker file</a></div></div>;
}
function Stat({ icon: Icon, label, value, tone }: { icon: typeof Bot; label: string; value: string; tone: string }) { return <div className="rounded-2xl border border-white/8 bg-[#0d101a] p-4"><div className={`grid size-9 place-items-center rounded-xl stat-${tone}`}><Icon className="size-4" /></div><div className="mt-4 text-2xl font-semibold tracking-tight">{value}</div><div className="mt-1 text-xs text-white/45">{label}</div></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm"><span className="mb-2 block text-xs font-medium text-white/52">{label}</span>{children}</label>; }
function Meta({ icon: Icon, label, value }: { icon: typeof Bot; label: string; value: string }) { return <div className="rounded-xl bg-white/[.035] p-3"><div className="flex items-center gap-1.5 text-[11px] text-white/30"><Icon className="size-3.5" />{label}</div><div className="mt-1.5 truncate text-sm capitalize text-white/75">{value}</div></div>; }
function Control({ label }: { label: string }) { return <div className="flex items-center gap-2"><div className="grid size-5 place-items-center rounded-full bg-emerald-400/10"><Check className="size-3 text-emerald-300" /></div><span className="text-white/65">{label}</span></div>; }
function Step({ number, text }: { number: string; text: string }) { return <div className="rounded-xl bg-white/[.035] p-3"><div className="text-xs font-medium text-violet-300">{number}</div><div className="mt-1.5 text-xs leading-5 text-white/45">{text}</div></div>; }
function Empty({ icon: Icon, title, text, action, onAction }: { icon: typeof Bot; title: string; text: string; action: string; onAction: () => void }) { return <section className="grid min-h-72 place-items-center rounded-2xl border border-dashed border-white/10 bg-white/[.018] p-8 text-center"><div><div className="mx-auto grid size-12 place-items-center rounded-2xl bg-violet-400/10 text-violet-300"><Icon className="size-5" /></div><h2 className="mt-4 font-semibold">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-white/40">{text}</p><Button onClick={onAction} className="mt-5 bg-violet-500 text-white hover:bg-violet-400">{action}<ChevronRight /></Button></div></section>; }
function Loading() { return <div className="grid min-h-72 place-items-center"><Loader2 className="size-6 animate-spin text-violet-300" /></div>; }
function relative(timestamp: number) { const seconds = Math.max(1, Math.round((Date.now() - timestamp) / 1000)); if (seconds < 60) return `${seconds}s ago`; if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`; if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`; return new Date(timestamp).toLocaleDateString(); }
